# Add deno completions to search path
if [[ ":$FPATH:" != *":$HOME/.zsh/completions:"* ]]; then
  export FPATH="$HOME/.zsh/completions:$FPATH";
fi
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -x "$(which zoxide)" ] && eval "$(zoxide init zsh)"

[ -f ~/.tokenrc ] && source ~/.tokenrc

# Vi mode
bindkey -v
export KEYTIMEOUT=22
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "hh" vi-cmd-mode
bindkey "jj" vi-cmd-mode
bindkey "^P" history-substring-search-up
bindkey "^N" history-substring-search-down
bindkey "^K" kill-line
bindkey "^U" backward-kill-line
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
# TODO: figure out when to add this
# export PATH="/opt/homebrew/opt/python@3.12/libexec/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# deno
[ -s "$HOME/.deno/env" ] && source "$HOME/.deno/env"
