# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/posva/.zsh/completions:"* ]]; then export FPATH="/Users/posva/.zsh/completions:$FPATH"; fi

# override tmux value so undercurl is shown
if [ "$TMUX" ]; then
  export TERM=xterm-256color
fi

# Add deno completions to search path
if [[ ":$FPATH:" != *":$HOME/.zsh/completions:"* ]]; then
  export FPATH="$HOME/.zsh/completions:$FPATH";
fi
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

[ -x "$(which zoxide)" ] && eval "$(zoxide init zsh)"

[ -f ~/.tokenrc ] && source ~/.tokenrc

# Vi mode
bindkey -v
export KEYTIMEOUT=22
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "hh" vi-cmd-mode
bindkey "jj" vi-cmd-mode
bindkey "^P" history-substring-search-up
bindkey "^N" history-substring-search-down
bindkey "^K" kill-line
bindkey "^U" backward-kill-line

eval "$(pyenv init - zsh)"

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
